recipes/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from rest_framework_swagger.views import get_swagger_view

from recipes.api.ingredient import IngredientViewSet
from recipes.api.planning import CalendarViewSet
from recipes.api.recipe import RecipeViewSet
from recipes.views.planning_pages import MonthViewSet, PlannerViewSet
from recipes.views.recipe_pages import RecipeViewSet as RecipePageViewSet

# This defines the app_name that is used to scope url names within this app
app_name = 'planner'

# Create a router and register our API view-sets
api_router = DefaultRouter()
api_router.register(r'ingredients', IngredientViewSet)
api_router.register(r'recipes', RecipeViewSet)
api_router.register(r'calendars', CalendarViewSet, base_name='calendar')

# Create a set of urlpatterns that only include the API
api_urlpatterns = [url(r'^api/', include(api_router.urls, namespace="api")), ]

# Show the API endpoints only on the Swagger page
schema_view = get_swagger_view(title='RecipLees API', patterns=api_urlpatterns, url='/planner/')

# Create a router to route all the other pages (the HTML pages)
page_router = DefaultRouter()
page_router.register(r'recipes', RecipePageViewSet, base_name='recipes')
page_router.register(r'months', MonthViewSet, base_name='months')
page_router.register(r'', PlannerViewSet, base_name='planner')

# And now create the final list of all API endpoints to allow proper routing
urlpatterns = api_urlpatterns + [
    url(r'^swagger/', schema_view, name='swagger'),  # Swagger API documentation page
    url(r'^', include(page_router.urls)),  # Main page views
]

reciplees/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView as tv

from recipes.views.utility_pages import server_version_data

handler404 = 'recipes.views.utility_pages.handle404'

urlpatterns = [

    # Authentication pages
    url(r'accounts/', include('django.contrib.auth.urls')),

    # Administration page for adding recipes, etc.
    url(r'^admin/', admin.site.urls, name="admin"),

    # Main app pages
    url(r'^planner/', include('recipes.urls')),

    # "About" page with Git sha and version info
    url(r'^about/', server_version_data, name='about'),

    # For robots and humans
    url(r'^robots.txt$', tv.as_view(template_name="common/robots.txt", content_type="text/plain"), name="robots_file"),
    url(r'^humans.txt$', tv.as_view(template_name="common/humans.txt", content_type="text/plain"), name="humans_file"),

    # Root home page
    url(r'^$', tv.as_view(template_name='common/home.html', content_type="text/html"), name="home")

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/common/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <title>
        {% block title %}Cait.Rocks!{% endblock %}
    </title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'ubuntu-fontface/ubuntu.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <style>
        #mainBodyContainer { padding-top: 15px; }
    </style>
    {% block extra_css %}{% endblock %}

</head>

<body style="font-family: Ubuntu, sans-serif;" {% block body_ng_declarations %}{% endblock %}>

{% block navbar %}
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark navbar-fixed-top" style="border-radius: 0;">
        <h1 class="navbar-brand mb-0">
            <a class="navbar-brand" href="{% url 'home' %}">Cait.Rocks</a>
        </h1>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mynavbar"
                aria-controls="mynavbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="mynavbar">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'planner:planner-list' %}">PlanningTool</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'planner:recipe_views-list' %}">Recipes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'planner:months-list' %}">MonthlyPlans</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about' %}">About</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if not request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'planner:swagger' %}">API</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout-{{ user.username }}</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
{% endblock %}

<div class="container-fluid" id="mainBodyContainer">
    <div class="row-fluid">
        <div class="col-12">
            {% block content %}{% endblock %}
        </div>
    </div>
</div>

<script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'angular/angular.min.js' %}"></script>
{% block extra_js %}{% endblock %}

</body>

</html>